spring:
  profiles:
    active: local
---
spring:
  profiles: local

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
    platform: h2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

mybatis:
  type-aliases-package: com.example.demo.model