DROP TABLE IF EXISTS UserProfile;

CREATE TABLE UserProfile (id int primary key , name varchar(64), phone varchar(64), address varchar(256));

drop table if exists member CASCADE;
create table member
(
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);